### ISSUE TITLE
Inf/NaN encountered during landmark calculation

### ISSUE THREAD

**Issue by wilkieolin** [scottgigante/m-phate#2]
I'm trying to use M-PHATE to visualize changes going on in a neural network during a continual learning method - the network is quite a bit larger than the examples (2400 hidden neurons total), and the transformation crashed during the landmark operator calculation. According to the traceback, there were Inf or NaN values encountered. Earlier in the graph/diffusion operator calculation, there was also a warning that invalid values were encountered. 

I don't see any invalid data or discrepancies in the input tensor which would easily explain the issue. I'm not very familiar with the graphical operations going on under the hood, is it possible that there is a parameter which needs to change for the larger number of hidden neurons or an issue in the code? The input tensor of activations I used is available [here](https://sunyit-my.sharepoint.com/:u:/g/personal/wo502482_sunycnse_com/EclTls4eWuVNg6NMIKfabxQBGYzye1nCuQDcIe0REghbmw?e=sqzs5d). 

```
Calculating M-PHATE...
  Calculating multislice kernel...
  Calculated multislice kernel in 233.67 seconds.
  Calculating graph and diffusion operator...

/home/wolin/anaconda3/envs/mphate/lib/python3.7/site-packages/scipy/sparse/compressed.py:213: RuntimeWarning: invalid value encountered in less
  res = self._with_data(op(self.data, other), copy=True)
/home/wolin/anaconda3/envs/mphate/lib/python3.7/site-packages/graphtools/graphs.py:1037: RuntimeWarning: invalid value encountered in less
  K.data[K.data < self.thresh] = 0

    Calculating landmark operator...
      Calculating SVD...
      Calculated SVD in 41.95 seconds.
    Calculated landmark operator in 41.95 seconds.
  Calculated graph and diffusion operator in 91.94 seconds.
Calculated M-PHATE in 326.34 seconds.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/mphate/lib/python3.7/site-packages/graphtools/graphs.py in landmark_op(self)
    588         try:
--> 589             return self._landmark_op
    590         except AttributeError:

AttributeError: 'TraditionalLandmarkGraph' object has no attribute '_landmark_op'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-141-aaf34eb39e68> in <module>
      1 # calculate M-PHATE
      2 m_phate_op = m_phate.M_PHATE()
----> 3 m_phate_data = m_phate_op.fit_transform(activations)

~/anaconda3/envs/mphate/lib/python3.7/site-packages/m_phate/m_phate.py in fit_transform(self, X, **kwargs)
    191         """
    192         with _logger.task('M-PHATE'):
--> 193             self.fit(X)
    194             embedding = self.transform(**kwargs)
    195         return embedding

~/anaconda3/envs/mphate/lib/python3.7/site-packages/m_phate/m_phate.py in fit(self, X)
    167                 random_state=self.random_state,
    168                 **(self.kwargs))
--> 169             self.diff_op
    170         result = super().fit(self.graph)
    171         return result

~/anaconda3/envs/mphate/lib/python3.7/site-packages/phate/phate.py in diff_op(self)
    274         if self.graph is not None:
    275             if isinstance(self.graph, graphtools.graphs.LandmarkGraph):
--> 276                 diff_op = self.graph.landmark_op
    277             else:
    278                 diff_op = self.graph.diff_op

~/anaconda3/envs/mphate/lib/python3.7/site-packages/graphtools/graphs.py in landmark_op(self)
    589             return self._landmark_op
    590         except AttributeError:
--> 591             self.build_landmark_op()
    592             return self._landmark_op
    593 

~/anaconda3/envs/mphate/lib/python3.7/site-packages/graphtools/graphs.py in build_landmark_op(self)
    659                     self.diff_aff,
    660                     n_components=self.n_svd,
--> 661                     random_state=self.random_state,
    662                 )
    663             with _logger.task("KMeans"):

~/anaconda3/envs/mphate/lib/python3.7/site-packages/sklearn/utils/extmath.py in randomized_svd(M, n_components, n_oversamples, n_iter, power_iteration_normalizer, transpose, flip_sign, random_state)
    346 
    347     Q = randomized_range_finder(M, n_random, n_iter,
--> 348                                 power_iteration_normalizer, random_state)
    349 
    350     # project M to the (k + p) dimensional space using the basis vectors

~/anaconda3/envs/mphate/lib/python3.7/site-packages/sklearn/utils/extmath.py in randomized_range_finder(A, size, n_iter, power_iteration_normalizer, random_state)
    230             Q = safe_sparse_dot(A.T, Q)
    231         elif power_iteration_normalizer == 'LU':
--> 232             Q, _ = linalg.lu(safe_sparse_dot(A, Q), permute_l=True)
    233             Q, _ = linalg.lu(safe_sparse_dot(A.T, Q), permute_l=True)
    234         elif power_iteration_normalizer == 'QR':

~/anaconda3/envs/mphate/lib/python3.7/site-packages/scipy/linalg/decomp_lu.py in lu(a, permute_l, overwrite_a, check_finite)
    208     """
    209     if check_finite:
--> 210         a1 = asarray_chkfinite(a)
    211     else:
    212         a1 = asarray(a)

~/anaconda3/envs/mphate/lib/python3.7/site-packages/numpy/lib/function_base.py in asarray_chkfinite(a, dtype, order)
    497     if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
    498         raise ValueError(
--> 499             "array must not contain infs or NaNs")
    500     return a
    501 

ValueError: array must not contain infs or NaNs
```

**Comment by scottgigante** [comment]
Any chance you can post a pickle of the trace tensor? I suspect this might be to do with zero distances but I'm not 100% sure. Are you using relu by any chance ?

**Comment by wilkieolin** [comment]
By trace do you mean the object created by the traceHistory function? I'm doing my training for the network using a custom algorithm outside of Keras, so I was hoping to just re-create the *epoch x activations x example* tensor and provide that information directly to the algorithm. These are calculated using ReLU units. 

I also noticed that in the console there's another error related to the intraslice bandwith, which it looks like is calculated as zero and causes the other issues down the line. From my understanding, this could be the case if many neurons are embedded in the same location, correct?

```
/home/wolin/anaconda3/envs/mphate/lib/python3.7/site-packages/m_phate/kernel.py:24: RuntimeWarning: divide by zero encountered in true_divide
  A = np.exp(-1 * (D / bandwidth)**2)
```

**Comment by scottgigante** [comment]
Yes, by the trace tensor I mean that _epoch x activations x example_ tensor. It sounds like the relu / zero distance issue is indeed the problem. If you are happy to send me the tensor I'll dig through and see how best to solve the problem.

**Comment by wilkieolin** [comment]
Sure, the tensor is [available as a pickle here](https://sunyit-my.sharepoint.com/:u:/g/personal/wo502482_sunycnse_com/ET0jlXOp9VlMv2aJA9aocjUBC8uBXsY2nPuwclyih14sew?e=LJi817). Thanks for looking into it!

**Comment by scottgigante** [comment]
Hi @wilkieolin , I think the issue is resolved on master. Do you mind trying it out and letting me know how it goes? I would also be interested in seeing the visualization it produces if you don't mind sharing!

**Comment by wilkieolin** [comment]
It works perfectly this time, thanks for fixing the issue!
The visualizations are quite interesting and I'm looking forward to digging into them more - we're looking at STDP-induced changes in performance and it's interesting at first glance to see that some large groups of neurons seem to be changing their representations at the same time.

![mphate_epoch](https://user-images.githubusercontent.com/10157823/73572186-05341700-4425-11ea-945d-f105bcf4d7b6.png)

**Comment by scottgigante** [comment]
Fascinating! Looking forward to seeing what comes of it. Best of luck.
