### ISSUE TITLE
PyTorch support

### ISSUE THREAD

**Issue by choltz95** [scottgigante/m-phate#3]
Hi! Thanks for the great project! I am interested in using your package w/ PyTorch networks. 

Do you have pointers? I guess the key piece is the _History object?

If it's easy to do, maybe I can help with the PR :)

**Comment by scottgigante** [comment]
To be honest, I haven't used PyTorch so I'm not sure how to implement this, though I don't imagine it would be too hard.

The key is to write a class or function that, given a network and a set of example inputs, will store the activations of all hidden units at the end of each batch/epoch.

In pseudo python, it looks like this:
```
Input: data [nxd], sample_size, epochs, hidden_sizes

sample_idx = sample_size random integers from 1 to n
sample_data = data[sample_idx]
hidden_layers = [hidden_layer(size) for size in hidden_sizes]

function TrainWithTrace(
  data, sample_data. epochs, hidden_layers
) -> trace [epochs x sum(hidden_sizes) x sample_size]
  trace = list()
  for epoch in range(epochs):
    Train(hidden_layers, data)
    trace.append(vstack([layer(sample_data) for layer in hidden_layers]))
  return trace
```

**Comment by choltz95** [comment]
So PyTorch doesn't support callbacks like Keras does. I guess the best way to use pytorch w/ m-phate is to just to emulate your TF notebook - e.g. https://github.com/scottgigante/m-phate/blob/master/examples/classification_tensorflow.ipynb
